import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Loyal.uz",
  description: "Generated by create next Loyal - yuridik firmasi sizga biznes, shaxsiy daxlsizlik, mualliflik, mulk, yer, soliq, uy-joy, ta'lim va boshqa huquqlaingizni himoya qilishga yordam beradi ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}